spring.application.name=test-task

spring.datasource.url=jdbc:postgresql://localhost:5432/test-task-shop
spring.datasource.username=postgres
spring.datasource.password=9745

openai.api-key=${OPENAI_API_KEY:}
openai.model=${OPENAI_MODEL:gpt-4.1-mini}
openai.base-url=${OPENAI_BASE_URL:https://api.openai.com}

